# Generated by Django 5.0.2 on 2024-02-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowingBooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
